[package]
name = "test_engine"
version = "0.1.0"
authors = ["Ryan J. Evans <me@rjevans.net>"]

[dependencies]
gl = "0.6.0"
stb_image = "*"
specs = "*"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["bundled", "static-link"]